#!/bin/bash

if [[ $1 == -o ]]; then
echo enabling original drivers
sudo modprobe dvb_usb_rtl28xxu
sudo modprobe rtl2830
sudo modprobe rtl2832
sudo modprobe mn88473
fi 

if [[ $1 == -r ]]; then
echo unloading original drivers
sudo modprobe -r dvb_usb_rtl28xxu
sudo modprobe -r rtl2830
sudo modprobe -r rtl2832
sudo modprobe -r mn88473
fi 

if [[ $1 == -s ]]; then
echo renaming frontends
sudo mv /dev/dvb/adapter0/frontend0 /dev/dvb/adapter0/frontend2
sudo mv /dev/dvb/adapter0/frontend1 /dev/dvb/adapter0/frontend0
fi

if [[ $1 == -h ]]; then
echo "-r: remove original drivers"
echo "-o: enable original drivers"
echo "-s: rename frontend1 to frontend0 for use in vlc"
fi
